{"name": "Если создать пользователя с логином, который уже есть, возвращается ошибка", "status": "passed", "steps": [{"name": "Создание курьера", "status": "passed", "parameters": [{"name": "login", "value": "'pablo_the_courier'"}, {"name": "password", "value": "'qwerty123456'"}, {"name": "first_name", "value": "'pablo'"}], "start": 1713184444023, "stop": 1713184444115}], "start": 1713184444023, "stop": 1713184444116, "uuid": "fbbfee6e-c414-478e-89b1-c88c44fff876", "historyId": "c7568512b6d10874e036c6b77f5dbb1a", "testCaseId": "29885fd3736cb99e68227d7d273b05aa", "fullName": "test_courier_creation.TestCourierCreation#test_create_existing_login_courier_error", "labels": [{"name": "story", "value": "Создание курьеров"}, {"name": "suite", "value": "test_courier_creation"}, {"name": "subSuite", "value": "TestCourierCreation"}, {"name": "host", "value": "pavel-Inspiron-3501"}, {"name": "thread", "value": "11408-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_courier_creation"}]}