{"name": "Система вернёт ошибку, если неправильно указать логин", "status": "passed", "steps": [{"name": "Логин курьера в системе", "status": "passed", "parameters": [{"name": "login", "value": "'pablo_the_courierwrong login for sure'"}, {"name": "password", "value": "'qwerty123456'"}], "start": 1713184562885, "stop": 1713184562971}], "start": 1713184562885, "stop": 1713184562971, "uuid": "3efc8ef3-7d1b-407e-b2c2-d489aa443f40", "historyId": "96829cfaa7090a8e5b4096d434d4c6f8", "testCaseId": "ddcad0836f12097c2334b6ed2728c714", "fullName": "test_courier_login.TestCourierLogin#test_courier_login_error_login", "labels": [{"name": "story", "value": "Проверка авторизации курьеров"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "pavel-Inspiron-3501"}, {"name": "thread", "value": "11706-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_courier_login"}]}